### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by Ashleyotero** [Ashleyotero/westloan-com#7]
When loading the document page in the admin panel:

An exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not find a part of the path 'C:\Users\csalinas\Source\Repos\westloan-com\Westloan.Web.Application\wwwroot\data\documents.json'.

**Comment by mlynam** [comment]
fixed this with b651f0aa93a3969e26b61d051e6029c5e550dbcb
